services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mercurjs
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    image: ghcr.io/marcjazz/hublots-marketplace/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    depends_on:
      - postgres

  storefront:
    image: ghcr.io/marcjazz/hublots-marketplace/storefront:latest
    build:
      context: ./storefront
      dockerfile: Dockerfile
    ports:
      - '8000:3000'
    depends_on:
      - backend

  admin-panel:
    image: ghcr.io/marcjazz/hublots-marketplace/admin-panel:latest
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    ports:
      - '7000:3000'
    depends_on:
      - backend

  vendor-panel:
    image: ghcr.io/marcjazz/hublots-marketplace/vendor-panel:latest
    build:
      context: ./vendor-panel
      dockerfile: Dockerfile
    ports:
      - '7001:3000'
    depends_on:
      - backend

volumes:
  pgdata:
