name: Static Artifacts Release

on:
  push:
    # tags:
    #   - '*'
    paths:
      - "admin-panel/**"
      - "vendor-panel/**"
      - ".github/workflows/static-artifacts.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        panel: [admin-panel, vendor-panel]
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: ${{ matrix.panel }}/pnpm-lock.yaml

      - name: Build Panel
        run: |
          cd ${{ matrix.panel }}
          pnpm install
          pnpm build:preview
        shell: bash

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: "projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WIP_POOL }}/providers/${{ secrets.WIP_PROVIDER }}"
          service_account: ${{ secrets.GHA_SERVICE_ACCOUNT }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Grant IAM Permissions"
        run: |
          gcloud iam service-accounts add-iam-policy-binding ${{ secrets.GHA_SERVICE_ACCOUNT }} \
              --role="roles/iam.workloadIdentityUser" \
              --member="principalSet://iam.googleapis.com/projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WIP_POOL }}/attribute.repository/${{ github.repository }}" \
              --project="${{ secrets.GCP_PROJECT_ID }}"
          gcloud iam service-accounts add-iam-policy-binding ${{ secrets.GHA_SERVICE_ACCOUNT }} \
              --role="roles/iam.serviceAccountTokenCreator" \
              --member="principalSet://iam.googleapis.com/projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WIP_POOL }}/attribute.repository/${{ github.repository }}" \
              --project="${{ secrets.GCP_PROJECT_ID }}"
          gcloud iam service-accounts add-iam-policy-binding ${{ secrets.GHA_SERVICE_ACCOUNT }} \
              --role="roles/storage.objectAdmin" \
              --member="principalSet://iam.googleapis.com/projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WIP_POOL }}/attribute.repository/${{ github.repository }}" \
              --project="${{ secrets.GCP_PROJECT_ID }}"
          gcloud iam service-accounts add-iam-policy-binding ${{ secrets.GHA_SERVICE_ACCOUNT }} \
              --role="roles/storage.admin" \
              --member="principalSet://iam.googleapis.com/projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WIP_POOL }}/attribute.repository/${{ github.repository }}" \
              --project="${{ secrets.GCP_PROJECT_ID }}"
        shell: bash

      - name: "Deploy to GCS"
        run: |
          if [ "${{ matrix.panel }}" = "admin-panel" ]; then
            BUCKET_NAME="hublots-admin-static"
          else
            BUCKET_NAME="hublots-vendor-static"
          fi
          gcloud storage rsync ${{ matrix.panel }}/dist gs://$BUCKET_NAME --recursive --delete-unmatched-destination-objects
          gcloud storage objects update gs://$BUCKET_NAME --recursive --cache-control="public, max-age=3600"
        shell: bash
        env:
          CLOUDSDK_AUTH_ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}

      - name: Tar Panel
        run: |
          cd ${{ matrix.panel }}
          tar -czf ../${{ matrix.panel }}-${{ github.ref_name }}.tar.gz dist
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.panel }}-archive
          path: ${{ matrix.panel }}-${{ github.ref_name }}.tar.gz
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: release-assets/*/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
